name: main
on: push

jobs:
  job1:
   name: JOB1
   runs-on: ubuntu-latest
   steps:
     - name: running single command on linux
       run: echo'Hi, This is my first job'
     - name: get linux os version details
       run: cat /etc/os-release
